### ISSUE TITLE
PyPI links to outdated Jug documentation on pythonhosted.org

### ISSUE THREAD

**Issue by andsor** [luispedro/jug#24]
I just realized there is an up-to-date documentation on http://jug.readthedocs.org/en/latest/

Previously, duckduckgo [1] referred me to http://pythonhosted.org/Jug/
This old version is also linked on PyPI: https://pypi.python.org/pypi/Jug ("Package documentation")

[1] https://duckduckgo.com/?t=lm&q=python+jug&ia=about

**Comment by luispedro** [comment]
Thanks for noticing this.

Apparently, it's hard to remove that old pythonhosted link, so I replaced by a redirect to the readthedocs version (which is nicer because it's auto-generated from github).

**Comment by andsor** [comment]
Excellent, thanks!
