### ISSUE TITLE
Jug reruns tasks with more than one keyword argument

### ISSUE THREAD

**Issue by andsor** [luispedro/jug#25]
When one supplies a task with several keyword arguments, [jug stores them in a dictionary](http://github.com/luispedro/jug/blob/43f0d80a78f418fd3aa2b8705eaf7c4a5175fff7/jug/task.py#L72).
Subsequently, [jug computes the hash by iterating through the dictionary](http://github.com/luispedro/jug/blob/43f0d80a78f418fd3aa2b8705eaf7c4a5175fff7/jug/task.py#L242).
This implicitly orders the dictionary when [updating the hash of the task](http://github.com/luispedro/jug/blob/422440af092e6df5c362679628aa8c3e928c30e3/jug/hash.py#L48).
However, the order of keyword arguments (or a dictionary) is undefined in Python < 3.5 (cf. [PEP 0468](http://www.python.org/dev/peps/pep-0468/)). Hence the implicit change of order of the supplied keyword arguments leads to recomputation of the task (if that particular order has not been computed before).

**Comment by andsor** [comment]
A possible solution is to [sort the keys in the Task constructor](http://github.com/luispedro/jug/blob/43f0d80a78f418fd3aa2b8705eaf7c4a5175fff7/jug/task.py#L72) and store the keyword arguments in an [OrderedDict](http://docs.python.org/3/library/collections.html#collections.OrderedDict).

**Comment by luispedro** [comment]
Good catch. I prefer another solution to using ordered dicts: pass the dictionary directly to ``hash_update`` as it sorts the keys itself (I'll commit in a few)

**Comment by andsor** [comment]
Ah excellent I missed that!
