### ISSUE TITLE
Premature "No tasks can be run" if a lot of small tasks are processed?

### ISSUE THREAD

**Issue by andsor** [luispedro/jug#33]
Ola @luispedro ,
during my simulations I came across this.

I assume that a lot of workers were doing small tasks, and then I assume [jug exits the loop prematurely here](https://github.com/luispedro/jug/blob/68390d73a720c837f3f5b44cc7fdb3642a118be1/jug/jug.py#L161) as all upnext tasks can be loaded in the mean time. This loop is outside the [wait cycles loop](https://github.com/luispedro/jug/blob/68390d73a720c837f3f5b44cc7fdb3642a118be1/jug/jug.py#L131), and hence I assume that only the [outer execution loop](https://github.com/luispedro/jug/blob/68390d73a720c837f3f5b44cc7fdb3642a118be1/jug/jug.py#L260) captures this case, but only twice before exiting.

Well, I know that a jug task should be of decent size for a reason, but I still would consider this is something to think about, if I am not mistaken in my assumptions here.

The number of actually running workers was about 80, and 14 of them exited prematurely like this. Everything else works like a charm, no exceptions occurred.

Complete stdout error log http://pastebin.com/vjTYHthD of one worker
Jugfile http://pastebin.com/hqwMCzXM

```
        gridjug.grid_jug(
            jugfile=BOND_PERCOLATION_JUGFILE,
            jugdir=BOND_PERCOLATION_JUGDIR,
            jug_args=[
                '--aggressive-unload',
            ],
            jug_nworkers=400,
            keep_going=True,
            verbose=True,
            **GRIDMAP_PARAMS
        )
```

**Comment by luispedro** [comment]
Yes, you are right. This is a bug. It solves some other problems (like a bunch of tasks doing an active spin of hitting the disk all the time), but it can still fail.

I will see if I can improve it.

**Comment by andsor** [comment]
Thank you! Is adding an option to actively circumvent this behaviour an option, as a quick-and-dirty fix?
