### ISSUE TITLE
Will jug create a lot of overhead in clusters

### ISSUE THREAD

**Issue by mistguy** [luispedro/jug#35]
I want to run a simple script in a cluster whose network transmission rate is relatively low. Processes in my script, if created by multiprocess module, have little communication with each other.

However, since jug need IO over network during execution, will it create a lot of overhead here?

**Comment by luispedro** [comment]
There isn't any IO over the network, except to transmit intermediate results and for synchronization. If your tasks have little communication with each other, then there will be little IO. It shouldn't be an issue.
