### ISSUE TITLE
Feature request: timing report for tasks

### ISSUE THREAD

**Issue by HeinerTholen** [luispedro/jug#36]
Somewhere in the documentation it says that one should have tasks that last at least for 2 or 3 seconds. In order to tune this (e.g. via `map_step`and `reduce_step` in mapreduce) it would be nice to have a report of the timing of the tasks. 
This could be an extra column in the summary that is printed by every worker, but it would also be nice to have it accessible through the results of a task (which would allow for automatic tuning). 

Many many thanks for this awesome tool! It's great. =)

**Comment by luispedro** [comment]
This was added in commit https://github.com/luispedro/jug/commit/098629073582bdbc9fff3f0fd13a6443776b56c4
