### ISSUE TITLE
Raises error if jugdir is not defined

### ISSUE THREAD

**Issue by rjplevin** [luispedro/jug#40]
If jugdir is not provided on command-line to "jug execute", and there is no jug config file, the program errors out, since this is prior to getting to the call to init() which handles the missing jugdir.

Just define a default:

    parser.add_option('--jugdir',
                    action='store',
                    dest='jugdir',
                    default='jugdir', # define default value
                    help='Where to save intermediate results')

**Comment by luispedro** [comment]
Can you tell me more about the error you are getting? What is the command line and what is the error.

There is a default already defined through the 'default_options' object. If you are getting an error, it means that this mechanism is not working.

Thank you

**Comment by rjplevin** [comment]
Sure. I'm just trying to get started with jug, so this all newbie stuff... I created a jugfile.py and ran "jug execute jugfile.py" without specifying a jugdir. Error occurs in line 317 of options.py, where cmdline.jugfile is referenced. I added the default as in my 1st message and it solve the problem.

    cmdline.jugdir = cmdline.jugdir % {
                'date': datetime.now().strftime('%Y-%m-%d'),
                'jugfile': cmdline.jugfile[:-3],
                }

**Comment by rjplevin** [comment]
Another minor error: in shell.py, IPython is referenced but not imported. Adding it in the "try" block solved the problem:

def shell(store, options, jugspace):
    '''
    shell(store, options, jugspace)

    Implement 'shell' command.

    Currently depends on Ipython being installed.
    '''
    try:
        import IPython
        if IPython.version_info[0]>=1:

**Comment by luispedro** [comment]
Thanks for the review. I think this is fixed on master, but it's perhaps high time to release a bug fix.

**Comment by rjplevin** [comment]
I had installed it, but now I cloned the repo so I'll be working off master. Thanks for the tip.

**Comment by luispedro** [comment]
There was a release shortly after this discussion, but I had forgotten to close the issue.
