### ISSUE TITLE
Is it possible to pass options into jugfile?

### ISSUE THREAD

**Issue by persmule** [luispedro/jug#41]
I am implementing a distributing calculation system with jug. I want to know whether it is possible to pass some options to jugfile from the command line of jug(1) or elsewhere, rather than let jugfile read them itself.

**Comment by luispedro** [comment]
Yes, it is, just pass them in and read them from ``sys.argv``.

This is not really an issue in the sense of a bug/feature request. Please use the mailing-list for this sort of queries:

https://groups.google.com/forum/#!forum/jug-users
