### ISSUE TITLE
CompoundTaskGenerator

### ISSUE THREAD

**Issue by alansaul** [luispedro/jug#43]
Hello, I was wondering whether there was a reason why CompoundTaskGenerator is not in the __init__.py

Is this feature still working? Or is it deprecated, still in progress, or just forgotten?

Great project by the way, it has been very useful!

**Comment by luispedro** [comment]
Thanks.

I think the only reason is that it was forgotten. Often new features start as an obscure import and later get promoted if they prove useful. This one just never got promoted.

**Comment by luispedro** [comment]
It should work just fine as advertised. Jug is pretty much solid stuff with maintenance work being done but not a lot of active development.

**Comment by luispedro** [comment]
Unrelated, but if you've used jug for a paper, I'd like to hear about it so I can cite it as an example of jug being useful: https://groups.google.com/forum/#!topic/jug-users/HuxC57Cq-98
