### ISSUE TITLE
Config file is never read

### ISSUE THREAD

**Issue by danpf** [luispedro/jug#44]
Could just be a linux thing (not sure what you develop on) but the tildes are not expanded in the function:
read_configuration_file(fp=None).  This results in never passing the IOERROR check, and thus, the jugrc file never being loaded (at least on my comp)
I think you have to use path.expanduser(fp) to replace the fp in the path.exists check and the open(fp) function.

Sadly though when I do that and get past the IOERROR check I get the error

File "/usr/local/lib/python3.5/dist-packages/Jug-1.4.0+git-py3.5.egg/jug/options.py", line 299, in parse
    'jugfile': cmdline.jugfile[:-3],
ValueError: unsupported format character 'j' (0x6a) at index 11

So clearly I'm missing something in the bigger picture!

**Comment by luispedro** [comment]
I think the first issue you raised is a good catch and a bona fides error. I will commit a fix asap.

The second issue may depend on what exactly your configuration file and command line look like.

**Comment by luispedro** [comment]
Please post more information (and either reopen this issue or open a new one) for the second issue you are reporting.
