### ISSUE TITLE
Config file may be read incorrectly

### ISSUE THREAD

**Issue by danpf** [luispedro/jug#45]
I had a long message typed out, and then I realized what the problem was :(

Depending on what your intentions are for the config file to be able to comprehend this could be a bug , or it's just a documentation error.
This is from http://jug.readthedocs.io/en/latest/configuration.html?highlight=config
```

[main]
jugdir=%(jugfile).jugdata
jugfile=jugfile.py

[status]
cache=off

[execute]
aggressive-unload=False
pdb=False
wait-cycle-time=12
nr-wait-cycles=150
```
This yeilds the error:
```
%(jugfile).jugdata
Traceback (most recent call last):
  File "/usr/local/bin/jug", line 9, in <module>
    load_entry_point('Jug==1.4.0+git', 'console_scripts', 'jug')()
  File "/usr/local/lib/python3.5/dist-packages/Jug-1.4.0+git-py3.5.egg/jug/jug.py", line 449, in main
    options = parse(argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/Jug-1.4.0+git-py3.5.egg/jug/options.py", line 302, in parse
    'jugfile': cmdline.jugfile[:-3],
ValueError: unsupported format character 'j' (0x6a) at index 11

```

if you change 
jugdir=%(jugfile).jugdata
to:
jugdir=jugfile.jugdata 

everything works fine

A fix for this would be to drop the % {} notation, and switch this and the documentation to python .format notation.

the result would be a config file that looks like this:
```
[main]
jugfile=jugfile.py
jugdir={jugfile}.{date}.jugdata

```
and your implementation in the source would look like:
```
    cmdline.jugdir = cmdline.jugdir.format(
                date=datetime.now().strftime('%Y-%m-%d'),
                jugfile=cmdline.jugfile[:-3])

```
IMO this is cleaner from a config file perspective, and code readability perspective

For reference it used to be:
```
    cmdline.jugdir = cmdline.jugdir % {
                'date': datetime.now().strftime('%Y-%m-%d'),
                'jugfile': cmdline.jugfile[:-3],
                }
```
Which is a format I've never used, so therefore know nothing about, maybe it's a quick fix?

**Comment by luispedro** [comment]
1. With the current system, the example is wrong, it should have been `%(jugfile)s.jugdata` (note the extra `s`). This is the old-school Python `%`-based formatting. I just fixed the docs.

2. I think your suggestion to use `format` style output is a good one, but breaks backwards compatibility. Perhaps automatically detecting which one is used is necessary.

**Comment by danpf** [comment]
I think the current way is fine, if it makes sense to you, that's all that matters!  Thanks for fixing the docs!
