### ISSUE TITLE
Racing issue with NFS file backend

### ISSUE THREAD

**Issue by quz2004** [luispedro/jug#6]
Hi, First I'd like to thank you guys creating jug, which is very convenient to use for embarrassingly parallel problems.

However I have found a bug using jug on a cluster (PBS). I used file backend and I did find racing problems. The simple task I used for testing is this:

#====================
myID = 'procid.%s.%s' % (str(os.getpid()) , os.environ['HOSTNAME'])

def createdir(d):
    if not os.path.isdir(d):
        os.mkdir(d)
        os.mkdir('%s/%s' % (d,myID))
    else:
        os.mkdir(d + '.' + myID)

@TaskGenerator
def runjob(cmd):
    hash = hashlib.md5(str(cmd)).hexdigest()
    createdir(hash)
    
cmds = [c.strip() for  c in open(joblistfile,'rt').read().splitlines() if c.strip() and not c.strip().startswith('#')]

for cmd in range(1024):
    runjob(str(cmd))
#==============================
I submitted two instances in two different nodes.
I found in the directory created by the task, there were dir names with "*.procid.*" which means racing condition did occur.

The reason I think is "O_EXCL is broken on NFS file systems," as described by GNU/Linux open(2) manpage. I would suggest using flufl.lock, which is safe over nfs:
http://pythonhosted.org/flufl.lock/docs/using.html

Thank you very much for your attention to the problem.

-Zheng Qu

**Comment by luispedro** [comment]
Jug is now more careful about calling ``fsync()`` in all the right places, so this (and other) issues is now probably no longer relevant. Please open a new bug report (with a newer version of jug) if you encounter any recent problems.
