### ISSUE TITLE
Ability to pass argument(s) that don't create new tasks

### ISSUE THREAD

**Issue by unode** [luispedro/jug#65]
I often find myself using the following code pattern:

```
if condition:
    TMPDIR = "/some/temp"
else:
    TMPDIR = "/tmp"

@TaskGenerator
def func(item):
    use_item(item, TMPDIR)
    ...
```

when I want to have variables that are used by the function but if changed do not result in different tasks.

Do you have any suggestion for how to handle this use-case?

----
An alternative could be to have a special argument that could be modified without generating new tasks.
Do you see the following as a reasonable proposal?

```
@TaskGenerator
def func(item, __jugbypass):
    tmpdir = __jugbypass["TMPDIR"]
    use_item(item, tmpdir)
    ...

if condition:
    TMPDIR = "/some/temp"
else:
    TMPDIR = "/tmp"

func(item, __jugbypass={"TMPDIR": TMPDIR})
```

The main advantage of the second example is the ability to reuse code across jugfiles.

**Comment by luispedro** [comment]
Global configuration variables are one options.

A hack is to define a class whose hash is always the same.

    class JugHidden(object):
        def __jug_hash__(self):
            return 'JugHidden'

Derive from `JugHidden`. This is just off the top of my head, so it may be wrong.

**Comment by unode** [comment]
I can work with that. Making the hash a fixed value is a resonable alternative. Thanks
