### ISSUE TITLE
Implement --target for jug cleanup

### ISSUE THREAD

**Issue by unode** [luispedro/jug#67]
I'm finding myself wanting to cleanup outputs of only some functions but not others.

Since `--target` already exists in other commands, would it be a viable option here?

**Comment by luispedro** [comment]
If I understand the question, this is impossible to implement with the current architecture.

Currently, `cleanup` deletes all the results whose hashes do not match a current task. If you would like to be more selective, however, you'd need to figure out where the hash is coming from (which is, to a first approximation, impossible) or have more information in the results file (which would add overhead).

**Comment by unode** [comment]
In #59 at https://github.com/luispedro/jug/pull/59/files#diff-b317a82b72a30159f25c028ad6194678R45 I extend cleanup to be able to remove only failed tasks.

Then on another custom-made user-command I use:

```python
        def run(self, store, options, *args, **kwargs):

            print("Failed tasks:")

            for t in task.alltasks:
                if not t.can_load() and t.is_failed():
                    try:
                        with open(t.store.getlock(t.hash()).fullname) as fh:
                            data = [line.rstrip() for line in fh]
                    except AttributeError:
                        # Not supported by the target backend
                        data = ""
                    print("  ", t.name, t.args, t.kwargs, " - ".join(data))

```
To list failed tasks.

This could be easily extended to remove that lock instead of reading from it's stored information.
Matching a target would be `t.name == options.target`.

Would this strategy be viable?
