### ISSUE TITLE
Processes only start working after checking status

### ISSUE THREAD

**Issue by chenxi-shi** [luispedro/jug#68]
When using 
`subprocess.Popen(["jug", "execute", "exmp.py"], stderr=STDOUT, creationflags=CREATE_NEW_CONSOLE) `
runing jug process, the subprocess will only starts after checking status.
The same thing happens when running by
`subprocess.Popen(["jug", "execute", "exmp.py"], stderr=STDOUT, shell=True) `

This problem doesn't appear when using 
`subprocess.Popen(["jug", "execute", "exmp.py"], stderr=STDOUT) `

Would you mind to help?

**Comment by luispedro** [comment]
I find it very surprising that there is a difference between these. What exactly do you mean by "checking status"?


Can you add the `--verbose=info` flag and see what happens?

**Comment by chenxi-shi** [comment]
Thank you for replying!
My "checking status" means the execution of "jug status exmp.py".

The subprocess code is in a file called "call_exmp.py", and the following is the print and I bold the time for your reference.

> \Jug_task>python call_exmp.py
call_exmp starts: 151861**8461**.5917778
process 9244: ['jug', 'execute', 'exmp.py', '--will-cite', '--verbose=INFO', '--debug']
process 4060: ['jug', 'execute', 'exmp.py', '--will-cite', '--verbose=INFO', '--debug']
process 11384: ['jug', 'execute', 'exmp.py', '--will-cite', '--verbose=INFO', '--debug']
process 12916: ['jug', 'execute', 'exmp.py', '--will-cite', '--verbose=INFO', '--debug']
\Jug_task>jug status exmp.py
Start: 151861**8481**.4294322
Spend 0.0019981861114501953
     Waiting       Ready    Finished     Running  Task name
.................................................................................................
           0           3           0           2  exmp.do_something
           1           0           0           0  exmp.join
.................................................................................................
           1           3           0           2  Total
C:\Mywork\tasks\Jug_task>

Here is the verbose information on one process.

> Start: 151861**8481**.130434
Spend 0.006001472473144531
INFO:root:Execute start (6 tasks)
INFO:root:Executing exmp.do_something...
0 Finished
INFO:root:Already in execution exmp.do_something...
INFO:root:Already in execution exmp.do_something...
INFO:root:Already in execution exmp.do_something...
INFO:root:Executing exmp.do_something...
6.343236446380615sec - Process 4: 1
7.344218969345093sec - Process 4: 2
8.34446907043457sec - Process 4: 3
9.345445156097412sec - Process 4: 4
4 Finished
INFO:root:Executing exmp.join...
___________________________This is join


I will also attach my test code in another comment for your reference.

**Comment by chenxi-shi** [comment]
Here are the screenshots of files
call_exmp.py
![call_exmp](https://user-images.githubusercontent.com/11368665/36209912-16fc278c-116b-11e8-8da0-faf66c84566c.PNG)
exmp.py
![exmp](https://user-images.githubusercontent.com/11368665/36209913-17082b4a-116b-11e8-8513-7a661a8c9d1a.PNG)

Thanks!

**Comment by chenxi-shi** [comment]
Updating:

This problem will be solved when I add `process.poll()`. It is like checking process would trigger the tasks' starting.

**Comment by luispedro** [comment]
Sorry, I cannot be more constructive, but I don't see why it shouldn't work as expected or why `process.poll()` would make a difference. If it's a windows thing then I cannot really help, though.

**Comment by chenxi-shi** [comment]
I am working on Windows. It doesn't matter since I could just use process.poll() to trigger processes. Thanks.

**Comment by luispedro** [comment]
Closing as I don't feel I have enough information to fix any underlying issue.
