### ISSUE TITLE
Jug throwing error, while running on PBS based HPC cluster

### ISSUE THREAD

**Issue by jaideep99** [luispedro/jug#80]
I've run the primes example given in docs, and the HPC I'm using has 5 nodes and PBS based. 

**qsub: invalid option --t**
Here's the error

jug execute "/home/jaideep.gedi.17cse/qgis/test.py" | qsub -t 1-100
qsub: invalid option -- 't'
usage: qsub [-a date_time] [-A account_string] [-c interval]
        [-C directive_prefix] [-e path] [-f ] [-h ] [-I [-X]] [-j oe|eo] [-J X-Y[:Z]]
        [-k o|e|oe] [-l resource_list] [-m mail_options] [-M user_list]
        [-N jobname] [-o path] [-p priority] [-P project] [-q queue] [-r y|n]
        [-S path] [-u user_list] [-W otherattributes=value...]
        [-v variable_list] [-V ] [-z] [script | -- command [arg1 ...]]
       qsub --version
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

Please look into this..

**Comment by luispedro** [comment]
This was answered on the mailing list, so closing here.

**Comment by luispedro** [comment]
https://groups.google.com/forum/#!topic/jug-users/nvDV1estS10

**Comment by jaideep99** [comment]
Can you also let me know how I can run the same thing through python console?
I have to use Jug in Qgis.

so I'm currently executing jug like this:

```
from subprocess import Popen, PIPE
import shlex
process = Popen(shlex.split("jug status '/home/jaideep.gedi.17cse/qgis/test.py'"), shell=False, universal_newlines=True,stdin=PIPE, stdout=PIPE, stderr=PIPE )
output, error = process.communicate();
print (output);
```
As qgis only provide its console, to handle the qgis project via python. So this is the only option I have which is running through the console.

Please suggest some way!
