### ISSUE TITLE
IterateTask as a decorator

### ISSUE THREAD

**Issue by justinrporter** [luispedro/jug#85]
I have been using a decorator to provide the functionality of `iteratetask` instead of the function.

The reason I like this is that it specifies how to handle the output (i.e. how many items in the tuple) closer to the place the output is specified (i.e. at the end of the function) rather than where the workflow is specified (which is usually a different file).

So it looks like:

```python
@IterateTask(n=3)
@jug.TaskGenerator
def do_thing(args):
    return a, b, c
```

I've been using the following for a few weeks without incident:

```python
import jug
from functools import wraps

def IterateTask(n):
    def decorator(f):
         @wraps(f)
         def wrapper(*args, **kwargs):
             return jug.iteratetask(f(*args, **kwargs), n=n)
         return wrapper
    return decorator
```

Is this something you'd be interested in adding? Is there any reason I haven't foreseen that this isn't a good idea?

**Comment by luispedro** [comment]
This seems like a good idea. If you could open a PR, I'd be happy to accept (only thing missing is some documentation and a test, AFAIK; but I can also help with that)

**Comment by justinrporter** [comment]
Wait is this what [return_tuple](https://github.com/luispedro/jug/blob/master/jug/task.py#L680) does? I happened across it when I was adding my decorator to `task.py` (where `iterate_task` is located).

**Comment by luispedro** [comment]
Yes, I had also forgotten about the existence of `return_tuple`, but it does seem to already be there

**Comment by luispedro** [comment]
I think we can close it here as the functionality is present as `return_tuple` (although, I would agree that the API is not very consistent in naming)

**Comment by justinrporter** [comment]
Agreed!
