### ISSUE TITLE
Allow cleanup of only locks

### ISSUE THREAD

**Issue by freemansw1** [luispedro/jug#86]
I recently had an issue with a few of my jug processes being killed and therefore locks being kept on some active tasks. Normally, I would just delete the lock files in the `jugdir`, but I was using the Redis backend, so this was not possible. As suggested in the docs, I ran `jug cleanup`, expecting only the locks to be cleared; I was surprised to find the completed jobs cleared as well. 

Is there any way to have `jug cleanup` only clear the locks? If not, can there be an option for this?

**Comment by luispedro** [comment]
1. There is `jug cleanup --only-locks`
2. Normally, `jug cleanup` should only clear old files. This is a bug with the `redis` backend!

**Comment by luispedro** [comment]
I just released `2.2.1` which fixes this.

**Comment by freemansw1** [comment]
Thanks so much for your incredibly rapid response!
